export function UsageGuide({ company, navigate, publish }: { company: boolean; navigate: (section: string) => void; publish: () => void }) {
  const steps = company ? [
    { title: "Prepara tu punto de recogida", text: "En Mi cuenta, toca tu ubicación en el mapa, revisa la dirección y guarda. Esa dirección sirve de referencia al publicar y buscar repartidores.", section: "profile", action: "Revisar mi ubicación" },
    { title: "Publica lo que necesitas enviar", text: "Indica los puntos de recogida y entrega, los horarios y la tarifa. Elige Público para llegar a los repartidores registrados, o Exclusivo de mi red para quienes aceptaron tu invitación.", section: "create", action: "Crear una entrega" },
    { title: "Elige cómo encontrar repartidor", text: "Puedes esperar a que acepten el trabajo o seleccionar una publicación en Buscar repartidores y enviar una propuesta a alguien disponible. Tiene hasta dos minutos para responder, o menos si vence la recogida. Enviar una propuesta no asigna automáticamente el trabajo.", section: "nearby", action: "Buscar repartidores" },
    { title: "Sigue los cambios de estado", text: "Abre el trabajo en Trabajos para consultar la recogida, la llegada y la notificación de entrega. El mapa de seguimiento requiere HALCON vinculado y que el repartidor comparta su GPS durante el trabajo activo.", section: "jobs", action: "Revisar trabajos" },
    { title: "Comprueba y confirma la entrega", text: "Cuando el repartidor notifique la entrega, verifica que se realizó antes de confirmar. Puedes solicitar revisión con un motivo. Para calificar a un repartidor, tu empresa debe haber confirmado al menos tres entregas suyas.", section: "jobs", action: "Ver entregas" },
  ] : [
    { title: "Revisa tu ubicación de referencia", text: "En Mi cuenta, toca el mapa y guarda la dirección. Se usa para ordenar las recogidas cercanas; guardar el perfil no activa el envío de GPS.", section: "profile", action: "Revisar mi ubicación" },
    { title: "Encuentra un trabajo que puedas realizar", text: "En Trabajos verás publicaciones públicas y las de las redes que hayas aceptado. Revisa direcciones, horarios y tarifa antes de aceptar. Puedes actualizar el orden con Ordenar cerca de mí.", section: "jobs", action: "Buscar trabajo" },
    { title: "Revisa las propuestas a tiempo", text: "Para aparecer en la búsqueda de empresas, activa Mostrarme disponible en Trabajos. Esto comparte tu posición reciente para esa búsqueda. Las propuestas llegan a Propuestas: acepta o rechaza antes de que venza el plazo. Puedes dejar de mostrar tu ubicación cuando quieras.", section: "offers", action: "Ver propuestas" },
    { title: "Registra cada paso de la entrega", text: "Abre tu trabajo aceptado. Confirma la recogida, indica que estás en el punto de entrega y notifica la entrega a la empresa. La empresa debe comprobarla y confirmarla; también puede solicitar una revisión.", section: "jobs", action: "Abrir mis trabajos" },
    { title: "Comparte GPS sólo cuando lo necesites", text: "Vincula tu cuenta personal de HALCON y activa el GPS dentro del trabajo. Vincular no empieza a compartir automáticamente. Mantén la web abierta y con conexión: el navegador puede pausar los envíos al bloquear el móvil.", section: "halcon", action: "Configurar HALCON" },
  ];
  return <div className="usage-guide">
    <section className="panel guide-intro"><p className="eyebrow">GUÍA PARA {company ? "EMPRESAS" : "REPARTIDORES"}</p><h2>{company ? "De tu primera publicación a la entrega confirmada" : "De encontrar un trabajo a completar la entrega"}</h2><p>Empieza por el primer paso o ve directamente a la tarea que necesitas. Los botones te llevan a la sección correspondiente.</p></section>
    <ol className="guide-steps">{steps.map((step, index) => <li className="panel" key={step.title}><span className="guide-number" aria-hidden="true">{String(index + 1).padStart(2, "0")}</span><div><h3>{step.title}</h3><p>{step.text}</p><button onClick={() => step.section === "create" ? publish() : navigate(step.section)}>{step.action} <span aria-hidden="true">→</span></button></div></li>)}</ol>
    {company && <aside className="dashboard-tip" aria-label="Afiliación a tu red"><strong>Invita personas a tu red</strong><p>En Directorio puedes buscar repartidores por nombre, consultar sus puntuaciones e invitarlos. Deben aceptar la invitación para afiliarse. No necesitas su correo ni su ubicación.</p><button onClick={() => navigate("directory")}>Abrir directorio →</button></aside>}
    <aside className="dashboard-tip" aria-label="Tarifa, pago y horarios"><strong>Tarifa, pago y horarios</strong><p>CHITA coordina trabajos y registra su estado. El pago se acuerda entre las partes y se realiza fuera de CHITA. La plataforma no garantiza repartidores disponibles, tiempos de llegada ni seguimiento en segundo plano.</p></aside>
  </div>;
}
